### ISSUE TITLE
Minimum Viable Product

### ISSUE THREAD

**Issue by glensc** [glensc/php-alpine#4]
- [ ] Create docker sandbox for building #1 
- [ ] Import community/php7 from aports #2 
- [ ] Namespace php7 as php7.3 #3 
- [ ] Add php7.3-xdebug
- [ ] ...
- [ ] Publish .apk packages

**Comment by peter279k** [comment]
I will do more contributions on this forked repository since the original repository has been inactive for the period of the time :).

**Comment by glensc** [comment]
I don't need this myself anymore, as I found I can use pretty recent PHP versions from alpine own repositories:

```dockerfile
FROM alpine:3.9 AS php-7.2
RUN apk add php7

FROM alpine:3.12 AS php-7.3
RUN apk add php7

FROM alpine:edge AS php-7.4
RUN apk add php7

FROM alpine:edge AS php-8.0
RUN apk add php8
RUN ln -s php8 /usr/bin/php
```

And since I do not require multiple PHP versions in the same images, this is pretty satisfactory for me.

**Comment by peter279k** [comment]
Never mind. I will use this approach you mention :).
